
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/home/sykim/.local/lib/python3.12/site-packages/cmake/data/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/usr/local/bin/"
      - "/home/sykim/.local/bin/"
      - "/home/sykim/.local/share/pnpm/"
      - "/usr/bin/"
      - "/bin/"
      - "/home/sykim/.nvm/current/bin/"
      - "/home/sykim/.npm-global/bin/"
      - "/home/sykim/bin/"
      - "/home/sykim/.volta/bin/"
      - "/home/sykim/.asdf/shims/"
      - "/home/sykim/.bun/bin/"
      - "/home/sykim/.fnm/current/bin/"
    searched_directories:
      - "/usr/local/bin/uname"
      - "/home/sykim/.local/bin/uname"
      - "/home/sykim/.local/share/pnpm/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/usr/local/bin"
        - "/home/sykim/.local/bin"
        - "/home/sykim/.local/share/pnpm"
        - "/usr/bin"
        - "/bin"
        - "/home/sykim/.nvm/current/bin"
        - "/home/sykim/.npm-global/bin"
        - "/home/sykim/bin"
        - "/home/sykim/.volta/bin"
        - "/home/sykim/.asdf/shims"
        - "/home/sykim/.bun/bin"
        - "/home/sykim/.fnm/current/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/home/sykim/.local/lib/python3.12/site-packages/cmake/data/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.17.0-19-generic - x86_64
...
